### ISSUE TITLE
Block version for moodle 2.8

### ISSUE THREAD

**Issue by jordelca** [marxjohnson/moodle-block_accessibility#81]
Hi, 
 have been working with this block for moodle 2.7. I just updated my moodle to 2.8, and I realized that it doesn't work as expected. Is that a known issue? is there any quickfix?

Is there any scheduled deadline for the new version to be published?
regards
Jorge

**Comment by jordelca** [comment]
Hi again!
any news about this issue? just asking, no hurries.
Thanks

**Comment by hrvojegolcic** [comment]
In my case it doesn't work at all in 2.8. I'm still unable to resolve what
would be the reason. Will come back with a solution as soon I succeed.
Should take a few weeks more I guess as now I'm on holidays. Do you have
any idea as well?

**Comment by jordelca** [comment]
Hi again,
I think I found the problem. Css are loaded with content type: "text/html". Although the content type is initially set to "text/css", for some reason it is set back to "text/html" after config.php call. So I fixed it by moving config.php call to first line, so that once header is set content type is not modified.
Would that be a valid fix?
You dont need to answer right now, enjoy your holidays!

**Comment by hrvojegolcic** [comment]
Wow! Was it really that simple? :P Well many thanks to you for noticing it. I really appreciate it.
Content type is actually what causes bug in older versions of IE as well. I Did't notice so far.

I guess the best fix would be to change .php extension to .css extension as well because it only leads to confusion to people and browsers, wouldn't you agree? But then the server would need to be configured properly which is less likely

In few days I'll include a few more bugfixes and publish a new release. Thanks a lot once more for your contribution!

**Comment by hrvojegolcic** [comment]
During the day I'll publish a new version of a block (2.2.2) to a Moodle plugin repository. Thanks for everything

**Comment by jordelca** [comment]
Great! You are welcome, Im glad was able to help!
