### ISSUE TITLE
Portuguese-Brazilian translation

### ISSUE THREAD

**Issue by nandosabbath** [marxjohnson/moodle-block_accessibility#99]
I would like to help in translation plugin Accessibility for Moodle to Portuguese-Brazilian . How should I proceed?

**Comment by marxjohnson** [comment]
Thanks very much for the offer.  We already have most of the block translated into Portuguese-Brazilian, but there are some strings that have been added since the translation.  

You can help complete the translation by creating a fork of this repository, editing lang/pt-br/block_accessibility.php (you can just do it through the GitHub editing interface if that's easiest), and create a pull request.

**Comment by marxjohnson** [comment]
The Portuguese-Brazillian translation has now been updated.
